## FOR TEST AND DEVELOPMENT ONLY, DO NOT USE IN PRODUCTION   ##

services:
  ## MariaDB (Database Server)
  ## Docs: https://mariadb.com/docs/reference/
  ## Release Notes: https://mariadb.com/kb/en/changes-improvements-in-mariadb-1011/
  mariadb:
    image: mariadb:11
    stop_grace_period: 10s
    security_opt: # see https://github.com/MariaDB/mariadb-docker/issues/434#issuecomment-1136151239
      - seccomp:unconfined
      - apparmor:unconfined
    command: --port=4001 --innodb-strict-mode=1 --innodb-buffer-pool-size=256M --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=120
    expose:
      - "4001" # 3306 isn't used intentionally to avoid conflicts and confuse port scanners
    ports:
      - "4001:4001" # MariaDB port (host:container)
    volumes:
      - "mariadb:/var/lib/mysql"
      - "./scripts/sql/mariadb-init.sql:/docker-entrypoint-initdb.d/init.sql"
    environment:
      MARIADB_AUTO_UPGRADE: "1"
      MARIADB_INITDB_SKIP_TZINFO: "1"
      MARIADB_DATABASE: "photoprism"
      MARIADB_USER: "photoprism"
      MARIADB_PASSWORD: "photoprism"
      MARIADB_ROOT_PASSWORD: "photoprism"

  ## PostgreSQL (Database Server)
  ## Docs: https://www.postgresql.org/docs/current/index.html
  ## Release Notes: https://www.postgresql.org/docs/release/
  postgres:
    image: pgvector/pgvector:pg18-trixie
    stop_grace_period: 15s
    expose:
      - "5432"
    ports:
      - "4002:5432" # PostgreSQL port (host:container)  5432 isn't used intentionally to avoid conflicts
    volumes:
      - "postgres:/var/lib/postgresql"
      - "./scripts/sql/postgresql-init.sql:/docker-entrypoint-initdb.d/init.sql"
    environment:
      POSTGRES_DB: photoprism
      POSTGRES_USER: photoprism
      POSTGRES_PASSWORD: photoprism
      PGDATA: /var/lib/postgresql/18/docker

  ## Qdrant (Vector Database)
  ## Docs: https://qdrant.tech/documentation/guides/installation/#docker-compose
  ## Release Notes: https://github.com/qdrant/qdrant/releases
  ## Web UI: https://qdrant.localssl.dev/dashboard
  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    depends_on:
      - traefik
    # profiles: [ "all", "qdrant" ]
    stop_grace_period: 10s
    links:
      - "traefik:localssl.dev"
      - "traefik:app.localssl.dev"
      - "traefik:vision.localssl.dev"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=vector"
      - "traefik.http.services.qdrant.loadbalancer.server.port=6333"
      - "traefik.http.services.qdrant.loadbalancer.server.scheme=http"
      - "traefik.http.routers.qdrant.entrypoints=websecure"
      - "traefik.http.routers.qdrant.rule=Host(`qdrant.localssl.dev`)"
      - "traefik.http.routers.qdrant.priority=3"
      - "traefik.http.routers.qdrant.tls.domains[0].main=localssl.dev"
      - "traefik.http.routers.qdrant.tls.domains[0].sans=*.localssl.dev"
      - "traefik.http.routers.qdrant.tls=true"
    expose:
      - "6333"
      - "6334"
      - "6335"
    ports:
      - "6333:6333"
      - "6334:6334"
      - "6335:6335"
    volumes:
      - "./.qdrant.yaml:/qdrant/config/production.yaml"
      - "./storage/services/qdrant:/qdrant/storage"

  ## Traefik v3 (Reverse Proxy)
  ## includes "*.localssl.dev" SSL certificate for test environments
  ## Docs: https://doc.traefik.io/traefik/
  traefik:
    image: photoprism/traefik:latest
    stop_grace_period: 15s
    security_opt:
      - no-new-privileges:true
    ports:
      - "80:80" # HTTP (redirects to HTTPS)
      - "443:443" # HTTPS (required)
    labels:
      - "traefik.enable=true"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock" # enables Traefik to watch services

## Create named volumes
volumes:
  mariadb:
    driver: local
  postgres:
    driver: local

## Create shared "vector" network for connecting with services in other compose.yaml files
networks:
  default:
    name: vector
    driver: bridge
